const {app,BrowserWindow,ipcMain,shell}=require('electron');
const fs=require('fs'),path=require('path'),os=require('os'),https=require('https'),http=require('http');
const {execFile}=require('child_process');
let win=null;
const DEFAULT={companyName:'CODEOCEAN',productName:'Exam Zone',businessType:'EdTech / Assessment Platform',description:'منصة اختبارات وتدريب وتحليلات أداء للمؤسسات والمدرسين.',targetCustomer:'أكاديميات ومراكز ومدارس ومدرسون لديهم طلاب ويحتاجون اختبارات وتدريب وتحليلات ومتابعة رقمية.',valueProposition:'اختبارات وتدريبات وتحليلات للطلاب باسم المؤسسة مع متابعة رقمية منظمة.',countries:['Saudi Arabia','Egypt','UAE'],dailyTarget:15};
const fresh=()=>({version:'0.6.0',onboardingDone:false,business:{...DEFAULT},settings:{ollamaModel:'qwen3:4b'},leads:[],tasks:[],messages:[{role:'assistant',content:'أنا CODEOCEAN Sales Brain. Exam Zone هو النشاط الافتراضي. قولّي محتاج عملاء منين ونوعهم إيه.'}]});
const store=()=>path.join(app.getPath('userData'),'sales-brain.json');
function read(){try{const x=JSON.parse(fs.readFileSync(store(),'utf8'));return {...fresh(),...x,business:{...DEFAULT,...(x.business||{})},settings:{ollamaModel:'qwen3:4b',...(x.settings||{})}}}catch{return fresh()}}
function write(s){fs.mkdirSync(path.dirname(store()),{recursive:true});fs.writeFileSync(store(),JSON.stringify(s,null,2));return s}
const emit=(type,text)=>{if(win&&!win.isDestroyed())win.webContents.send('progress',{type,text})};
const now=()=>new Date().toISOString(),uid=p=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
const clean=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
function req(url,opts={}){return new Promise((resolve,reject)=>{let u;try{u=new URL(url)}catch{return reject(Error('bad url'))}const lib=u.protocol==='http:'?http:https;const r=lib.request(u,{method:opts.method||'GET',headers:{'User-Agent':'Mozilla/5.0 Windows Chrome/126','Accept':'text/html,application/json,*/*',...(opts.headers||{})},timeout:opts.timeout||12000},res=>{let d='';res.setEncoding('utf8');res.on('data',c=>{if(d.length<1500000)d+=c});res.on('end',()=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){return resolve(req(new URL(res.headers.location,u).href,opts))}resolve({status:res.statusCode||0,text:d})})});r.on('timeout',()=>r.destroy(Error('timeout')));r.on('error',reject);if(opts.body)r.write(opts.body);r.end()})}
function norm(url){try{if(url.startsWith('//'))url='https:'+url;const u=new URL(url);if(u.hostname.includes('duckduckgo.com')&&u.pathname.startsWith('/l/'))return decodeURIComponent(u.searchParams.get('uddg')||url);return u.href}catch{return''}}
async function search(q,limit=25){const out=[],seen=new Set();try{const r=await req('https://html.duckduckgo.com/html/?q='+encodeURIComponent(q),{timeout:15000});const re=/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(r.text))&&out.length<limit){const url=norm(m[1]);if(url&&!seen.has(url)){seen.add(url);out.push({url,title:clean(m[2])})}}}catch{}if(out.length<5){try{const r=await req('https://www.bing.com/search?q='+encodeURIComponent(q)+'&count='+limit);const re=/<li class="b_algo"[\s\S]*?<h2><a href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(r.text))&&out.length<limit){const url=norm(m[1]);if(url&&!seen.has(url)){seen.add(url);out.push({url,title:clean(m[2])})}}}catch{}}return out}
function contacts(html,base){const links=[];const rr=/href\s*=\s*["']([^"']+)["']/gi;let m;while((m=rr.exec(html))&&links.length<300){try{links.push(new URL(m[1],base).href)}catch{}}const txt=clean(html).slice(0,90000);const phones=txt.match(/(?:\+?\d[\d\s().-]{7,}\d)/g)||[];const phone=phones.find(x=>x.replace(/\D/g,'').length>=9)||'';const pick=f=>links.find(x=>x.toLowerCase().includes(f))||'';const title=clean((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'');return{phone,title,whatsapp:pick('wa.me')||pick('whatsapp.com'),tiktok:pick('tiktok.com'),facebook:pick('facebook.com'),instagram:pick('instagram.com')}}
const channel=l=>l.whatsapp?'WhatsApp':l.tiktok?'TikTok':l.facebook?'Facebook':l.instagram?'Instagram':l.phone?'Phone':'Website';
function score(l){let s=35;if(l.website)s+=10;if(l.phone)s+=10;if(l.whatsapp)s+=18;if(l.tiktok)s+=12;if(l.facebook)s+=8;if(l.instagram)s+=7;return Math.min(100,s)}
function pitch(l,b){if((b.productName||'').toLowerCase()==='exam zone')return 'السلام عليكم 👋 شفت '+l.name+' وحبيت أتواصل لأن Exam Zone ممكن يضيف لكم اختبارات وتدريبات وتحليل مستوى الطلاب داخل تجربة باسم المؤسسة. أقدر أجهز Demo صغير مخصص بدون التزام، مناسب أبعت التفاصيل؟';return 'أهلًا 👋 تابعت '+l.name+' وشايف توافق محتمل مع '+b.productName+'. '+b.valueProposition+' لو مناسب أقدر أبعت مثال سريع مخصص لنشاطكم.'}
async function hunt(o={}){const s=read(),b=s.business;const count=Math.max(1,Math.min(Number(o.count||b.dailyTarget||15),40));const city=o.city||'',country=o.country||b.countries?.[0]||'',target=o.target||b.targetCustomer;const q=[target,o.specialization||'',city,country,'WhatsApp TikTok Facebook'].filter(Boolean).join(' ');emit('search','Searching: '+q);const rs=await search(q,Math.max(20,count*3));const found=[],hosts=new Set();for(let i=0;i<rs.length&&found.length<count;i++){const r=rs[i];emit('verify','Verifying '+(i+1)+'/'+rs.length+': '+(r.title||r.url));let u;try{u=new URL(r.url)}catch{continue}const social=/tiktok\.com|facebook\.com|instagram\.com|wa\.me|whatsapp\.com/i.test(r.url);if(!social&&hosts.has(u.hostname))continue;hosts.add(u.hostname);let c={phone:'',title:'',whatsapp:'',tiktok:'',facebook:'',instagram:''};if(social){if(r.url.includes('tiktok.com'))c.tiktok=r.url;if(r.url.includes('facebook.com'))c.facebook=r.url;if(r.url.includes('instagram.com'))c.instagram=r.url;if(/wa\.me|whatsapp\.com/.test(r.url))c.whatsapp=r.url}else{try{const p=await req(r.url,{timeout:9000});if(p.status<400)c=contacts(p.text,r.url)}catch{}}const name=(c.title||r.title||u.hostname).split(/[|–—-]/)[0].trim().slice(0,100);const l={id:uid('lead'),name,city,country,segment:o.target||'Business',website:social?'':r.url,sourceUrl:r.url,phone:c.phone,whatsapp:c.whatsapp,tiktok:c.tiktok,facebook:c.facebook,instagram:c.instagram,verifiedAt:now(),status:'New',createdAt:now()};l.bestChannel=channel(l);l.score=score(l);l.priority=l.score>=80?'Hot':l.score>=65?'High':l.score>=50?'Medium':'Low';l.message=pitch(l,b);found.push(l)}const keys=new Set(s.leads.map(x=>(x.website||x.sourceUrl||x.name).toLowerCase()));const freshOnes=found.filter(x=>!keys.has((x.website||x.sourceUrl||x.name).toLowerCase()));s.leads.unshift(...freshOnes);freshOnes.filter(x=>x.score>=50).forEach(l=>s.tasks.push({id:uid('task'),leadId:l.id,title:'تواصل مع '+l.name,channel:l.bestChannel,status:'open',dueAt:now()}));write(s);emit('done','Found '+freshOnes.length+' new leads');return{state:s,found:freshOnes,query:q}}
function ps(cmd){return new Promise((resolve,reject)=>execFile('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-Command',cmd],{windowsHide:true},(e,stdout,stderr)=>e?reject(Error(stderr||e.message)):resolve(stdout)))}
async function ollamaStatus(){let installed=false,running=false,models=[];try{await ps('(Get-Command ollama -ErrorAction Stop).Source');installed=true}catch{}try{const r=await req('http://127.0.0.1:11434/api/tags',{timeout:2500});if(r.status<400){running=true;installed=true;models=(JSON.parse(r.text).models||[]).map(x=>x.name)}}catch{}const gb=Math.round(os.totalmem()/1073741824);return{installed,running,models,totalRamGB:gb,recommended:gb>=16?'qwen3:8b':'qwen3:4b'}}
async function ollamaChat(message){const s=read();const body=JSON.stringify({model:s.settings.ollamaModel,messages:[{role:'system',content:'You are CODEOCEAN Sales Brain. Be concise, practical, sales-focused. Business: '+JSON.stringify(s.business)},{role:'user',content:message}],stream:false});const r=await req('http://127.0.0.1:11434/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body,timeout:120000});return JSON.parse(r.text)?.message?.content||''}
function parseHunt(t,b){const n=Number((t.match(/\b(\d{1,2})\b/)||[])[1]||b.dailyTarget||15);const cities=['الرياض','جدة','دبي','أبوظبي','الكويت','الدوحة','القاهرة','الإسكندرية'];const city=cities.find(x=>t.includes(x))||'';let country='';if(/السعود|الرياض|جدة/.test(t))country='Saudi Arabia';else if(/الإمارات|دبي|أبوظبي/.test(t))country='UAE';else if(/مصر|القاهرة|الإسكندرية/.test(t))country='Egypt';let target=b.targetCustomer;if(/مطاعم|مطعم/.test(t))target='Restaurants';else if(/اكاديم|أكاديم|مراكز تعليم|مدارس/.test(t))target='Educational academies and centers';return{count:n,city,country,target}}
async function brain(t){let s=read();s.messages.push({role:'user',content:t});if(/ببيع|نشاطي|البيزنس|business/i.test(t)&&!/هات|دور|ابحث|search/i.test(t)){const m=t.replace(/^.*?(?:ببيع|نشاطي|البيزنس|business)\s*[:：-]?\s*/i,'').trim();if(m){s.business={...s.business,productName:m,businessType:'Custom Business',description:m,targetCustomer:'عملاء محتملون مناسبون لـ '+m,valueProposition:m};s.messages.push({role:'assistant',content:'تم تحديث Business Memory إلى: '+m});write(s);return{state:s}}}if(/هات|دور|ابحث|عايز.*عملاء|leads|search/i.test(t)){const o=parseHunt(t,s.business);const r=await hunt(o);s=r.state;s.messages.push({role:'assistant',content:'لقيت '+r.found.length+' Leads جديدة وتم ترتيبها وإضافة مهام التواصل.'});write(s);return{state:s,action:{type:'hunt',count:r.found.length}}}let answer='';try{answer=await ollamaChat(t)}catch{answer='أنا جاهز للبحث وإدارة المبيعات. مثال: هات 15 أكاديمية إنجليزي في الرياض. ومن الإعدادات تقدر تربط Ollama المحلي.'}s=read();s.messages.push({role:'assistant',content:answer});write(s);return{state:s}}
function create(){win=new BrowserWindow({width:1480,height:940,minWidth:1080,minHeight:720,backgroundColor:'#07111f',title:'CODEOCEAN Sales Brain',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}});win.maximize();win.loadFile(path.join(__dirname,'..','index.html'))}
app.whenReady().then(create);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
ipcMain.handle('state:get',()=>read());ipcMain.handle('business:save',(_,b)=>{const s=read();s.business={...s.business,...b};return write(s)});ipcMain.handle('business:reset',()=>{const s=read();s.business={...DEFAULT};return write(s)});ipcMain.handle('onboarding:done',()=>{const s=read();s.onboardingDone=true;return write(s)});ipcMain.handle('hunt',(_,o)=>hunt(o));ipcMain.handle('brain',(_,t)=>brain(t));
ipcMain.handle('lead:update',(_,id,p)=>{const s=read(),l=s.leads.find(x=>x.id===id);if(l)Object.assign(l,p);return write(s)});ipcMain.handle('task:toggle',(_,id)=>{const s=read(),t=s.tasks.find(x=>x.id===id);if(t)t.status=t.status==='done'?'open':'done';return write(s)});
ipcMain.handle('ollama:status',()=>ollamaStatus());ipcMain.handle('ollama:install',async()=>{emit('ollama','Installing Ollama…');await ps("irm https://ollama.com/install.ps1 | iex");emit('ollama','Ollama installed');return ollamaStatus()});ipcMain.handle('ollama:pull',async(_,m)=>{emit('ollama','Downloading '+m+'…');await ps('ollama pull '+m);return ollamaStatus()});ipcMain.handle('ollama:select',(_,m)=>{const s=read();s.settings.ollamaModel=m;return write(s)});ipcMain.handle('external',(_,u)=>shell.openExternal(u));